DEF_ERROR(OK,                   "Everything is ok!")
DEF_ERROR(BAD_POINTER_TREE,     "Bad pointer of tree was passed in function")
DEF_ERROR(BAD_POINTER_NODE,     "Bad pointer of node was passed in function")
DEF_ERROR(BAD_POINTER_STR,      "Bad pointer of string was passed in function")
DEF_ERROR(BAD_CALLOC,           "Error in calloc when create new node")
DEF_ERROR(BAD_OPEN_FILE,        "Error in openning file")
DEF_ERROR(BAD_CLOSE_FILE,       "Error in closing file")
DEF_ERROR(ROOT_NULL,            "Root of tree became null")
DEF_ERROR(BAD_VALUE_OF_DATA,    "The value of data is bad")
DEF_ERROR(LOOP_IN_TREE,         "Find loop in tree")
DEF_ERROR(TREE_SEARCH_NOT_DONE, "Error in recursive tree searching")
DEF_ERROR(BAD_FILESTREAM,       "Bad filestream passed in function")
DEF_ERROR(BAD_ANSWER,           "Unknown answer")
DEF_ERROR(NODE_HAVE_ONE_BRANCH, "Node have one branch but its shit!")
DEF_ERROR(BAD_POINTER_STACK,    "Bad pointer of stack passed in function")
DEF_ERROR(BAD_POINTER_FILE,     "Bad pointer of file passed in function")
DEF_ERROR(BAD_IN_READ_FILE,     "Size of result fread not equal to ")
DEF_ERROR(OVERFLOW_VARIABLE,    "Buffer of value is overflow")
DEF_ERROR(WHAT_FILE_OF_DATA,    "While compiling you need to write in what file save data")
DEF_ERROR(BAD_POINTER_DATA,     "Bad pointer of data was passed in function")
DEF_ERROR(BAD_REC_SCAN,         "Recursion scanning tree is break")
DEF_ERROR(NO_OPEN_BRACKET_NODE, "No open bracket of node like <(>")
DEF_ERROR(NO_CLOSE_BRACKET_NODE,"No close bracket of node like <)>")
DEF_ERROR(NO_OPEN_BRACKET_OBJ,  "No open bracket of node like <(>")
DEF_ERROR(BAD_FREAD,            "Size of return fread not equal to size_text")
DEF_ERROR(OVERFLOW_BUFF,        "Buffer of buffer is overflow")
DEF_ERROR(PROCESS_OBJECT,       "Some errors in process object")
DEF_ERROR(INIT_NODE,            "In tree there is init node, but how???")
DEF_ERROR(UNKNOWN_TYPE,         "In tree some unknown type")
DEF_ERROR(NO_FILE_TO_OPEN,      "There is no file to open! You forgot to create its")
DEF_ERROR(REC_DIFF,             "In differentiators recursion is trouble!")

DEF_ERROR(DIV_ZERO,             "In calculating we saw a divizion on zero! Its bad, we stop programm :(")
DEF_ERROR(SQRT_MINUS,           "In calculating we saw a sqrt(<0)! Its bad, we stop programm :(")
DEF_ERROR(POW_NAN,              "In calculating we saw a 0^0! Its bad, we stop program :(")
DEF_ERROR(LOG_MINUS,            "In calculating we saw  a log(<0)! Its vad, we stop program :(")